services:
  valkey:
    image: mirror.gcr.io/valkey/valkey:8-alpine
    container_name: valkey
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - valkey_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  valkey_data:
    driver: local