services:
  dbgate:
    image: mirror.gcr.io/dbgate/dbgate:alpine
    container_name: dbgate
    volumes:
      - dbgate_data:/root/.dbgate
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  dbgate_data: