services:
  rabbitmq:
    image: mirror.gcr.io/rapidfort/rabbitmq-official:4-management-alpine
    container_name: rabbitmq
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  rabbitmq_data: