services:
  scylladb:
    image: mirror.gcr.io/scylladb/scylla:2025.3
    container_name: scylladb
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - scylladb_data:/var/lib/scylla
    ports:
      - "9042:9042"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  scylladb_data:
    driver: local