services:
  kafka:
    image: mirror.gcr.io/confluentinc/cp-kafka:7.4.10
    container_name: kafka
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - kafka_data:/var/lib/kafka
    ports:
      - "9092:9092"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  kafka_data: