services:
  redis:
    image: mirror.gcr.io/rapidfort/redis-official:8-alpine
    container_name: redis
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  redis_data: