services:
  clickhouse:
    image: clickhouse:latest
    container_name: clickhouse
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  clickhouse_data: