services:
  nats:
    image: mirror.gcr.io/nats:2-alpine
    container_name: nats
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - nats_data:/data
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  nats_data: