services:
  nats:
    image: mirror.gcr.io/nats:2
    container_name: my-nats-server
    command: -js # Enable JetStream for persistent messaging capabilities
    environment:
      TZ: ${TZ}
      LANG: ${LANG}
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Monitoring port
    volumes:
      - nats_data:/data # For JetStream persistence
    healthcheck:
      test:
        [
          "CMD",
          "nats-req",
          "--server",
          "nats://localhost:4222",
          "--timeout",
          "1s",
          "PING",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  nats_data:
    driver: local
