services:
  mariadb:
    image: mirror.gcr.io/rapidfort/mariadb-official:lts
    container_name: mariadb
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  mariadb_data: