services:
  traefik:
    image: mirror.gcr.io/rapidfort/traefik:3
    container_name: traefik
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - traefik_data:/var/lib/traefik
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ct_shared_network

volumes:
  traefik_data:
    driver: local